Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,9 +26,8 @@ jobs:
           nvidia-smi
           git clone http://www.github.com/xytpai/nvbench && cd nvbench
           bash build.sh standard/device_property.cu
-          exit_label=$(./a.out 2>&1 > /dev/null)
-          echo ${exit_label}
-          exit_label=$?
-          cat log
-          echo ${exit_label}
+          ./a.out
+          if [ $? -ne 0 ];then
+            echo "failure"
+          fi
           cd .. && rm -rf nvbench
